apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
data:
  databaseUrl: {{ .Values.env.databaseUrl | b64enc }}
  authServerUrl: {{ .Values.env.authServerUrl | b64enc }}
  authServerPathToken: {{ .Values.env.authServerPathToken | b64enc }}
  authServerPathAuthorize: {{ .Values.env.authServerPathAuthorize | b64enc }}
  wwwPaymentSuccessRedirectUrl: {{ .Values.env.wwwPaymentSuccessRedirectUrl | b64enc }}
  wwwPaymentCancelRedirectUrl: {{ .Values.env.wwwPaymentCancelRedirectUrl | b64enc }}
  paypalClientId: {{ .Values.env.paypalClientId | b64enc }}
  paypalClientSecret: {{ .Values.env.paypalClientSecret | b64enc }}
  paypalCallbackValidUrl: {{ .Values.env.paypalCallbackValidUrl | b64enc }}
  paypalCallbackCancelUrl: {{ .Values.env.paypalCallbackCancelUrl | b64enc }}
  cloudamqpUrl: {{ .Values.env.cloudamqpUrl | b64enc }}
  cloudamqpExchangeName: {{ .Values.env.cloudamqpExchangeName | b64enc }}
